language: node_js
node_js:
- 4.2
before_script:
- npm install -g grunt-cli
script:
- npm test && cat ./coverage/lcov.info | ./node_modules/.bin/codecov
notifications:
  email: false
deploy:
  provider: npm
  email: support@kuzzle.io
  api_key:
    secure: CRIT0iLcgDXG7ssC9NLBFvLz6uOUvM66jEKPFXGWMojibbZ7EZ6DTfXh1HigEd1YOtGFoOB1IuoXIevV3yuwSIvMEgv8gm4hSjJ1xwbH92iR4eV1i9BjW4d4wZ90gdjZ12TG8wh7c7BiiXG6tKxfOs8E5iG+4r4i0S/+HF6BDiYGbz83OrzFMH1ULJZWtE+cp5/Vhgb3n2tksI+gLQwOM4LAlsh1aB/90P6pBccVWBQcahDEzh63V6loZDYUgrqq0UTYWwOlrThK2Fs0NIzOO+nK5PvG2H8LS/IVFinzYVDUc9nI7C2SPcZWeIfOGiLh6BJn7bPovIXPPFW9KYR/WtV3qQDi6AgO/K85ijlfKstIt6WEHJRHYiOehNFOO/PlkM3UyBhPuG06BnKojxWH7O7MyH//e4y9TLSOEi9iKFeA8UgcidlRmkX7pGirGhuUXEBZ0c/GRjWIx8SKdiH1G4RK331uph4Un7SBCk604SRiNZZiaX0hoWQuheZBRTHEGtPMYbsGad1SOBIm2Umosay1JBnNiCXkGobwxejkFC5wrSr+hiutRMzsbBJ6lj7SlXWPwqwLzcsGct/0CrdWnm40VurTRzjit341l7eYxzFGN0KMvuObyfsM7ZvEWpxZjSOD8vdM6l9jJ7AhKs2aFvxOHjJywwHEU0zj0yVeEzU=
  on:
    branch: master
    repo: kuzzleio/kuzzle-plugin-websocket
