language: node_js
node_js:
- 4.2
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
before_install:
- export CC="gcc-4.9" CXX="g++-4.9"
script:
- npm test && cat ./coverage/lcov.info | ./node_modules/.bin/codecov
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/8e145155fbaaf37cffea
    on_success: change
    on_failure: always
    on_start: never
  email: false
deploy:
  provider: npm
  email: support@kuzzle.io
  api_key:
    secure: uoxkC16iPUs+f81s3AiEPJdiTr4zWGfM4eOs/GWzmbcWNwwe/Xe08UgXplbGnZdDMacXPrOeBeTOiqFpDai3jtQbQpHdSjoNAD7BoVWe6x/9osHJ0xTUDy9waEw+RCHTLTrwMCUyGCG05NG1A/o4nLsU2sJdP38p/ssOSR33caDDR8MtokNIlKxkXLJ1nz41miKBvzR+fVBGMitziUN0Ta1P8qodYt2cdLMoDfI/2/O5069CKcANinmoKpnNd2hpMUm6eYaTlol4QEofiYR0qEIQQZlmWua9ujtK/3oJGjLWkDKZm9BS0dpcbk/XqLWGUyH2ZzAt6ufljabKG+yWYHY9wSh3ZVfzjGticV1hOi3dgIJzGlIAhEYvEpSKxzmRXu8HsGdsOfMux5KxcDZacCBHiUjFbsWJUv0OXkO0KcFM76p/D6SrST0TN4wej7fD5EyO8GD8WogPjnEZ2odXnE198a2m358G+IY/OVJa1RscN+SRCAMFAuCfe6VMGOmsw0OOEYAgbOjeHWn9Fi6n9naliSlhZ+FuuGnHrpabAj/DoHXsPf87mF8hNmjGb3IEM/E5WbLoL9KoDpRzYs40RH364oyv4eu/tIijhEL2kWWOyyAWkPlkwzWGcfqwtCOw4mWGvYvb7bb0bzPHOmD4nSBr3odwz79n/jK2oEgZz3M=
  on:
    repo: kuzzleio/kuzzle-plugin-websocket
    branch: master
